# Disable PostgreSQL settings
# spring.datasource.url=jdbc:postgresql://database-1.cw5famkyqij5.us-east-1.rds.amazonaws.com:5432/db
# spring.datasource.username=your_user
# spring.datasource.password=your_pass

# Use H2 instead (easy, no setup)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
